### ISSUE TITLE
Ammonite REPL doesn't work well with Scala 2.11.8

### ISSUE THREAD

**Issue by liancheng** [liancheng/scraper#2]
```
$ build/sbt repl/run
[info] Running scraper.repl.Main
Loading...
[error] (run-main-9) java.lang.AbstractMethodError: ammonite.repl.interp.CompilerCompatibility$$anon$2.printingOk(Lscala/reflect/internal/Trees$Tree;)Z
java.lang.AbstractMethodError: ammonite.repl.interp.CompilerCompatibility$$anon$2.printingOk(Lscala/reflect/internal/Trees$Tree;)Z
        at scala.tools.nsc.typechecker.TypersTracking$class.noPrintAdapt(TypersTracking.scala:164)
        at ammonite.repl.interp.CompilerCompatibility$$anon$2.noPrintAdapt(CompilerCompatibility.scala:10)
        at scala.tools.nsc.typechecker.TypersTracking$typingStack$.showAdapt(TypersTracking.scala:115)
        at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5415)
        at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5423)
        at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5370)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5374)
        at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5472)
        at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5480)
        at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5012)
        at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5312)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5359)
        at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5396)
        at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5423)
        at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5370)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5374)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5448)
        at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:102)
        at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:440)
        at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:431)
        at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:440)
        at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:94)
        at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:93)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
        at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1501)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1486)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:1481)
        at scala.tools.nsc.Global$Run.compileFiles(Global.scala:1571)
        at ammonite.repl.interp.Compiler$$anon$4.compile(Compiler.scala:256)
        at ammonite.repl.interp.Interpreter$$anonfun$6$$anonfun$apply$7.apply(Interpreter.scala:339)
        at ammonite.repl.interp.Interpreter$$anonfun$6$$anonfun$apply$7.apply(Interpreter.scala:339)
        at ammonite.repl.interp.Evaluator$$anon$1.ammonite$repl$interp$Evaluator$$anon$$compileClass(Evaluator.scala:144)
        at ammonite.repl.interp.Evaluator$$anon$1.cachedCompileBlock(Evaluator.scala:288)
        at ammonite.repl.interp.Evaluator$$anon$1.processScriptBlock(Evaluator.scala:303)
        at ammonite.repl.interp.Interpreter$$anonfun$processModule$1.apply(Interpreter.scala:98)
        at ammonite.repl.interp.Interpreter$$anonfun$processModule$1.apply(Interpreter.scala:98)
        at ammonite.repl.interp.Interpreter.loop$1(Interpreter.scala:156)
        at ammonite.repl.interp.Interpreter.processScript(Interpreter.scala:169)
        at ammonite.repl.interp.Interpreter.processModule(Interpreter.scala:98)
        at ammonite.repl.interp.Interpreter.<init>(Interpreter.scala:400)
        at ammonite.repl.Repl.<init>(Repl.scala:38)
        at ammonite.repl.Main$.repl$lzycompute$1(Main.scala:130)
        at ammonite.repl.Main$.repl$1(Main.scala:130)
        at ammonite.repl.Main$.run(Main.scala:136)
        at scraper.repl.Main$.main(Main.scala:11)
        at scraper.repl.Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
```

Should probably downgrade Scala back to 2.11.7.

**Comment by liancheng** [comment]
Fixed by commit https://github.com/liancheng/scraper/commit/2ab1e8da01779b21194e1c888b31b0f2b488a1eb.
